In [ ]:
# Books Recommendation System

In [2]:
# Import Libraries
import numpy as np
import pandas as pd

In [3]:
# Load Dataset
df = pd.read_csv("books.csv")

df.head()

,book_id,title,author,genre,rating,image_url
0,1,Harry Potter,J.K. Rowling,Fantasy,4.8,https://covers.openlibrary.org/b/id/7984916-L.jpg
1,2,The Hobbit,J.R.R. Tolkien,Fantasy,4.7,https://covers.openlibrary.org/b/id/6979861-L.jpg
2,3,Atomic Habits,James Clear,Self-help,4.6,https://covers.openlibrary.org/b/id/9259256-L.jpg
3,4,Rich Dad Poor Dad,Robert Kiyosaki,Finance,4.5,https://covers.openlibrary.org/b/id/240726-L.jpg
4,5,Alchemist,Paulo Coelho,Fiction,4.4,https://covers.openlibrary.org/b/id/8277896-L.jpg

In [4]:
# Select Important Columns
df = df[['book_id','title','author','genre','rating']]
df = df.copy()

df.head()

   book_id              title           author      genre  rating
0        1       Harry Potter     J.K. Rowling    Fantasy     4.8
1        2         The Hobbit   J.R.R. Tolkien    Fantasy     4.7
2        3      Atomic Habits      James Clear  Self-help     4.6
3        4  Rich Dad Poor Dad  Robert Kiyosaki    Finance     4.5
4        5          Alchemist     Paulo Coelho    Fiction     4.4

In [5]:
# Handle Missing Values
df.isnull().sum()

book_id    0
title      0
author     0
genre      0
rating     0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
# Create Tags (Feature Engineering)
df['tags'] = df['title'] + " " + df['author'] + " " + df['genre']

df.head()

,book_id,title,author,genre,rating,tags
0,1,Harry Potter,J.K. Rowling,Fantasy,4.8,Harry Potter J.K. Rowling Fantasy
1,2,The Hobbit,J.R.R. Tolkien,Fantasy,4.7,The Hobbit J.R.R. Tolkien Fantasy
2,3,Atomic Habits,James Clear,Self-help,4.6,Atomic Habits James Clear Self-help
3,4,Rich Dad Poor Dad,Robert Kiyosaki,Finance,4.5,Rich Dad Poor Dad Robert Kiyosaki Finance
4,5,Alchemist,Paulo Coelho,Fiction,4.4,Alchemist Paulo Coelho Fiction

In [8]:
# Convert to Lowercase
df['tags'] = df['tags'].apply(lambda x: x.lower())

df.head()

,book_id,title,author,genre,rating,tags
0,1,Harry Potter,J.K. Rowling,Fantasy,4.8,harry potter j.k. rowling fantasy
1,2,The Hobbit,J.R.R. Tolkien,Fantasy,4.7,the hobbit j.r.r. tolkien fantasy
2,3,Atomic Habits,James Clear,Self-help,4.6,atomic habits james clear self-help
3,4,Rich Dad Poor Dad,Robert Kiyosaki,Finance,4.5,rich dad poor dad robert kiyosaki finance
4,5,Alchemist,Paulo Coelho,Fiction,4.4,alchemist paulo coelho fiction

In [9]:
# Convert to Lowercase
df['tags'] = df['tags'].apply(lambda x: x.lower())

df.head()

,book_id,title,author,genre,rating,tags
0,1,Harry Potter,J.K. Rowling,Fantasy,4.8,harry potter j.k. rowling fantasy
1,2,The Hobbit,J.R.R. Tolkien,Fantasy,4.7,the hobbit j.r.r. tolkien fantasy
2,3,Atomic Habits,James Clear,Self-help,4.6,atomic habits james clear self-help
3,4,Rich Dad Poor Dad,Robert Kiyosaki,Finance,4.5,rich dad poor dad robert kiyosaki finance
4,5,Alchemist,Paulo Coelho,Fiction,4.4,alchemist paulo coelho fiction

In [10]:
# Final DataFrame
new_df = df[['book_id','title','tags']]

new_df.head()

   book_id              title                                       tags
0        1       Harry Potter          harry potter j.k. rowling fantasy
1        2         The Hobbit          the hobbit j.r.r. tolkien fantasy
2        3      Atomic Habits        atomic habits james clear self-help
3        4  Rich Dad Poor Dad  rich dad poor dad robert kiyosaki finance
4        5          Alchemist             alchemist paulo coelho fiction

In [11]:
# Vectorization
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

vectors.shape

(7, 29)

In [12]:
# Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity.shape

(7, 7)

In [13]:
# Recommendation Function
def recommend(book):
    book = book.lower()

    if book not in new_df['title'].str.lower().values:
        print("Book not found!")
        return

    index = new_df[new_df['title'].str.lower() == book].index[0]

    distances = list(enumerate(similarity[index]))
    books_list = sorted(distances, key=lambda x: x[1], reverse=True)[1:6]

    print("Top 5 Recommendations:\n")
    for i, b in enumerate(books_list):
        print(i+1, ".", new_df.iloc[b[0]].title)

In [14]:
# Test
recommend("Harry Potter")

Top 5 Recommendations:

1 . The Hobbit
2 . Atomic Habits
3 . Rich Dad Poor Dad
4 . Alchemist
5 . Think and Grow Rich

In [15]:
# Save Model
import pickle

pickle.dump(new_df, open('books.pkl','wb'))
pickle.dump(similarity, open('books_similarity.pkl','wb'))